echo BUILDING FP_REFERENCE_MODEL

if [ -e "../build" ]
then
    echo Build folder exists
else
    echo Creating build folder
    mkdir ../build
fi

gcc -std=c99 -g reference_model.c \
             -o ../build/reference_model \
                source/common/fall_maxmin.c \
                source/common/fall_reciprocal.c \
                source/common/s_add128.c \
                source/common/s_add256M.c \
                source/common/s_addCarryM.c \
                source/common/s_addComplCarryM.c \
                source/common/s_addMagsF128.c \
                source/common/s_addMagsF16.c \
                source/common/s_addMagsF32.c \
                source/common/s_addMagsF64.c \
                source/common/s_addM.c \
                source/common/s_approxRecip_1Ks.c \
                source/common/s_approxRecip32_1.c \
                source/common/s_approxRecipSqrt_1Ks.c \
                source/common/s_approxRecipSqrt32_1.c \
                source/common/s_commonNaNToF128UI.c \
                source/common/s_commonNaNToF16UI.c \
                source/common/s_commonNaNToF32UI.c \
                source/common/s_commonNaNToF64UI.c \
                source/common/s_compare128M.c \
                source/common/s_compare96M.c \
                source/common/s_countLeadingZeros16.c \
                source/common/s_countLeadingZeros32.c \
                source/common/s_countLeadingZeros64.c \
                source/common/s_countLeadingZeros8.c \
                source/common/s_eq128.c \
                source/common/s_f128UIToCommonNaN.c \
                source/common/s_f16UIToCommonNaN.c \
                source/common/s_f32UIToCommonNaN.c \
                source/common/s_f64UIToCommonNaN.c \
                source/common/s_le128.c \
                source/common/s_lt128.c \
                source/common/s_mul128By32.c \
                source/common/s_mul128MTo256M.c \
                source/common/s_mul128To256M.c \
                source/common/s_mul64ByShifted32To128.c \
                source/common/s_mul64To128.c \
                source/common/s_mul64To128M.c \
                source/common/s_mulAddF128.c \
                source/common/s_mulAddF16.c \
                source/common/s_mulAddF32.c \
                source/common/s_mulAddF64.c \
                source/common/s_negXM.c \
                source/common/s_normRoundPackToF128.c \
                source/common/s_normRoundPackToF16.c \
                source/common/s_normRoundPackToF32.c \
                source/common/s_normRoundPackToF64.c \
                source/common/s_normSubnormalF128Sig.c \
                source/common/s_normSubnormalF16Sig.c \
                source/common/s_normSubnormalF32Sig.c \
                source/common/s_normSubnormalF64Sig.c \
                source/common/softfloat_raiseFlags.c \
                source/common/softfloat_state.c \
                source/common/s_propagateNaNF128UI.c \
                source/common/s_propagateNaNF16UI.c \
                source/common/s_propagateNaNF32UI.c \
                source/common/s_propagateNaNF64UI.c \
                source/common/s_remStepMBy32.c \
                source/common/s_roundMToI64.c \
                source/common/s_roundMToUI64.c \
                source/common/s_roundPackMToI64.c \
                source/common/s_roundPackMToUI64.c \
                source/common/s_roundPackToBF16.c \
                source/common/s_roundPackToF128.c \
                source/common/s_roundPackToF16.c \
                source/common/s_roundPackToF32.c \
                source/common/s_roundPackToF64.c \
                source/common/s_roundPackToI32.c \
                source/common/s_roundPackToI64.c \
                source/common/s_roundPackToUI32.c \
                source/common/s_roundPackToUI64.c \
                source/common/s_roundToI32.c \
                source/common/s_roundToI64.c \
                source/common/s_roundToUI32.c \
                source/common/s_roundToUI64.c \
                source/common/s_shiftRightJam128.c \
                source/common/s_shiftRightJam128Extra.c \
                source/common/s_shiftRightJam256M.c \
                source/common/s_shiftRightJam32.c \
                source/common/s_shiftRightJam64.c \
                source/common/s_shiftRightJam64Extra.c \
                source/common/s_shortShiftLeft128.c \
                source/common/s_shortShiftLeft64To96M.c \
                source/common/s_shortShiftRight128.c \
                source/common/s_shortShiftRightExtendM.c \
                source/common/s_shortShiftRightJam128.c \
                source/common/s_shortShiftRightJam128Extra.c \
                source/common/s_shortShiftRightJam64.c \
                source/common/s_shortShiftRightJam64Extra.c \
                source/common/s_shortShiftRightM.c \
                source/common/s_sub128.c \
                source/common/s_sub1XM.c \
                source/common/s_sub256M.c \
                source/common/s_subMagsF128.c \
                source/common/s_subMagsF16.c \
                source/common/s_subMagsF32.c \
                source/common/s_subMagsF64.c \
                source/common/s_subM.c \
                source/conversion/f128_to_f16.c \
                source/conversion/f128_to_f32.c \
                source/conversion/f128_to_f64.c \
                source/conversion/f128_to_i32.c \
                source/conversion/f128_to_i32_r_minMag.c \
                source/conversion/f128_to_i64.c \
                source/conversion/f128_to_i64_r_minMag.c \
                source/conversion/f128_to_ui32.c \
                source/conversion/f128_to_ui32_r_minMag.c \
                source/conversion/f128_to_ui64.c \
                source/conversion/f128_to_ui64_r_minMag.c \
                source/conversion/f16_to_f128.c \
                source/conversion/f16_to_f32.c \
                source/conversion/f16_to_f64.c \
                source/conversion/f16_to_i16.c \
                source/conversion/f16_to_i32.c \
                source/conversion/f16_to_i32_r_minMag.c \
                source/conversion/f16_to_i64.c \
                source/conversion/f16_to_i64_r_minMag.c \
                source/conversion/f16_to_i8.c \
                source/conversion/f16_to_ui16.c \
                source/conversion/f16_to_ui32.c \
                source/conversion/f16_to_ui32_r_minMag.c \
                source/conversion/f16_to_ui64.c \
                source/conversion/f16_to_ui64_r_minMag.c \
                source/conversion/f16_to_ui8.c \
                source/conversion/f32_to_f128.c \
                source/conversion/f32_to_f16.c \
                source/conversion/f32_to_f64.c \
                source/conversion/f32_to_i16.c \
                source/conversion/f32_to_i32.c \
                source/conversion/f32_to_i32_r_minMag.c \
                source/conversion/f32_to_i64.c \
                source/conversion/f32_to_i64_r_minMag.c \
                source/conversion/f32_to_ui16.c \
                source/conversion/f32_to_ui32.c \
                source/conversion/f32_to_ui32_r_minMag.c \
                source/conversion/f32_to_ui64.c \
                source/conversion/f32_to_ui64_r_minMag.c \
                source/conversion/f64_to_f128.c \
                source/conversion/f64_to_f16.c \
                source/conversion/f64_to_f32.c \
                source/conversion/f64_to_i32.c \
                source/conversion/f64_to_i32_r_minMag.c \
                source/conversion/f64_to_i64.c \
                source/conversion/f64_to_i64_r_minMag.c \
                source/conversion/f64_to_ui32.c \
                source/conversion/f64_to_ui32_r_minMag.c \
                source/conversion/f64_to_ui64.c \
                source/conversion/f64_to_ui64_r_minMag.c \
                source/conversion/i32_to_f128.c \
                source/conversion/i32_to_f16.c \
                source/conversion/i32_to_f32.c \
                source/conversion/i32_to_f64.c \
                source/conversion/i64_to_f128.c \
                source/conversion/i64_to_f16.c \
                source/conversion/i64_to_f32.c \
                source/conversion/i64_to_f64.c \
                source/conversion/ui32_to_f128.c \
                source/conversion/ui32_to_f16.c \
                source/conversion/ui32_to_f32.c \
                source/conversion/ui32_to_f64.c \
                source/conversion/ui64_to_f128.c \
                source/conversion/ui64_to_f16.c \
                source/conversion/ui64_to_f32.c \
                source/conversion/ui64_to_f64.c \
                source/softfloat_8/bf16_to_f8_1.c \
                source/softfloat_8/bf16_to_f8_2.c \
                source/softfloat_8/bf16_to_i8.c \
                source/softfloat_8/bf16_to_ui8.c \
                source/softfloat_8/f8_1_2_recip7_rsqrte7.c \
                source/softfloat_8/f8_1_add.c \
                source/softfloat_8/f8_1_classify.c \
                source/softfloat_8/f8_1_div.c \
                source/softfloat_8/f8_1_eq.c \
                source/softfloat_8/f8_1_le.c \
                source/softfloat_8/f8_1_lt.c \
                source/softfloat_8/f8_1_lt_quiet.c \
                source/softfloat_8/f8_1_max_min.c \
                source/softfloat_8/f8_1_mulAdd.c \
                source/softfloat_8/f8_1_mul.c \
                source/softfloat_8/f8_1_sqrt.c \
                source/softfloat_8/f8_1_sub.c \
                source/softfloat_8/f8_1_to_bf16.c \
                source/softfloat_8/f8_1_to_f8_2.c \
                source/softfloat_8/f8_1_to_i16.c \
                source/softfloat_8/f8_1_to_i32.c \
                source/softfloat_8/f8_1_to_i8.c \
                source/softfloat_8/f8_1_to_ui16.c \
                source/softfloat_8/f8_1_to_ui32.c \
                source/softfloat_8/f8_1_to_ui8.c \
                source/softfloat_8/f8_2_add.c \
                source/softfloat_8/f8_2_classify.c \
                source/softfloat_8/f8_2_div.c \
                source/softfloat_8/f8_2_eq.c \
                source/softfloat_8/f8_2_le.c \
                source/softfloat_8/f8_2_lt.c \
                source/softfloat_8/f8_2_lt_quiet.c \
                source/softfloat_8/f8_2_max_min.c \
                source/softfloat_8/f8_2_mulAdd.c \
                source/softfloat_8/f8_2_mul.c \
                source/softfloat_8/f8_2_sqrt.c \
                source/softfloat_8/f8_2_sub.c \
                source/softfloat_8/f8_2_to_bf16.c \
                source/softfloat_8/f8_2_to_f8_1.c \
                source/softfloat_8/f8_2_to_i16.c \
                source/softfloat_8/f8_2_to_i32.c \
                source/softfloat_8/f8_2_to_i8.c \
                source/softfloat_8/f8_2_to_ui16.c \
                source/softfloat_8/f8_2_to_ui32.c \
                source/softfloat_8/f8_2_to_ui8.c \
                source/softfloat_8/i8_to_bf16.c \
                source/softfloat_8/i16_to_f8_1.c \
                source/softfloat_8/i16_to_f8_2.c \
                source/softfloat_8/i32_to_f8_1.c \
                source/softfloat_8/i32_to_f8_2.c \
                source/softfloat_8/s_addMagsF8_1.c \
                source/softfloat_8/s_addMagsF8_2.c \
                source/softfloat_8/s_mulAddF8_1.c \
                source/softfloat_8/s_mulAddF8_2.c \
                source/softfloat_8/s_normRoundPackToF8_1.c \
                source/softfloat_8/s_normRoundPackToF8_2.c \
                source/softfloat_8/s_normSubnormalF8_1Sig.c \
                source/softfloat_8/s_normSubnormalF8_2Sig.c \
                source/softfloat_8/s_propagateNaNF8_1UI.c \
                source/softfloat_8/s_propagateNaNF8_2UI.c \
                source/softfloat_8/s_roundPackToF8_1.c \
                source/softfloat_8/s_roundPackToF8_2.c \
                source/softfloat_8/s_subMagsF8_1.c \
                source/softfloat_8/s_subMagsF8_2.c \
                source/softfloat_8/ui8_to_bf16.c \
                source/softfloat_8/ui16_to_f8_1.c \
                source/softfloat_8/ui16_to_f8_2.c \
                source/softfloat_8/ui32_to_f8_1.c \
                source/softfloat_8/ui32_to_f8_2.c \
                source/softfloat_16/f16_add.c \
                source/softfloat_16/f16_classify.c \
                source/softfloat_16/f16_div.c \
                source/softfloat_16/f16_eq.c \
                source/softfloat_16/f16_eq_signaling.c \
                source/softfloat_16/f16_isSignalingNaN.c \
                source/softfloat_16/f16_le.c \
                source/softfloat_16/f16_le_quiet.c \
                source/softfloat_16/f16_lt.c \
                source/softfloat_16/f16_lt_quiet.c \
                source/softfloat_16/f16_mulAdd.c \
                source/softfloat_16/f16_mul.c \
                source/softfloat_16/f16_rem.c \
                source/softfloat_16/f16_roundToInt.c \
                source/softfloat_16/f16_sqrt.c \
                source/softfloat_16/f16_sub.c \
                source/softfloat_32/f32_add.c \
                source/softfloat_32/f32_classify.c \
                source/softfloat_32/f32_div.c \
                source/softfloat_32/f32_eq.c \
                source/softfloat_32/f32_eq_signaling.c \
                source/softfloat_32/f32_isSignalingNaN.c \
                source/softfloat_32/f32_le.c \
                source/softfloat_32/f32_le_quiet.c \
                source/softfloat_32/f32_lt.c \
                source/softfloat_32/f32_lt_quiet.c \
                source/softfloat_32/f32_mulAdd.c \
                source/softfloat_32/f32_mul.c \
                source/softfloat_32/f32_rem.c \
                source/softfloat_32/f32_roundToInt.c \
                source/softfloat_32/f32_sqrt.c \
                source/softfloat_32/f32_sub.c \
                source/softfloat_64/f64_add.c \
                source/softfloat_64/f64_classify.c \
                source/softfloat_64/f64_div.c \
                source/softfloat_64/f64_eq.c \
                source/softfloat_64/f64_eq_signaling.c \
                source/softfloat_64/f64_isSignalingNaN.c \
                source/softfloat_64/f64_le.c \
                source/softfloat_64/f64_le_quiet.c \
                source/softfloat_64/f64_lt.c \
                source/softfloat_64/f64_lt_quiet.c \
                source/softfloat_64/f64_mulAdd.c \
                source/softfloat_64/f64_mul.c \
                source/softfloat_64/f64_rem.c \
                source/softfloat_64/f64_roundToInt.c \
                source/softfloat_64/f64_sqrt.c \
                source/softfloat_64/f64_sub.c \
                source/softfloat_128/f128_add.c \
                source/softfloat_128/f128_classify.c \
                source/softfloat_128/f128_div.c \
                source/softfloat_128/f128_eq.c \
                source/softfloat_128/f128_eq_signaling.c \
                source/softfloat_128/f128_isSignalingNaN.c \
                source/softfloat_128/f128_le.c \
                source/softfloat_128/f128_le_quiet.c \
                source/softfloat_128/f128_lt.c \
                source/softfloat_128/f128_lt_quiet.c \
                source/softfloat_128/f128_mulAdd.c \
                source/softfloat_128/f128_mul.c \
                source/softfloat_128/f128_rem.c \
                source/softfloat_128/f128_roundToInt.c \
                source/softfloat_128/f128_sqrt.c \
                source/softfloat_128/f128_sub.c \
                -lm \
                -I include